"""Trusted build/runtime templates generated by the platform."""

from __future__ import annotations

from dataclasses import dataclass

from mim_control_plane.domain.states import WorkloadKind
from mim_control_plane.services.classifier import WorkloadClassification


@dataclass(frozen=True, slots=True)
class BuildTemplate:
    kind: WorkloadKind
    runtime: str
    install_command: tuple[str, ...]
    build_command: tuple[str, ...]
    launch_command: tuple[str, ...]
    required_files: tuple[str, ...]
    schedule_cron: str | None = None


def build_template_for(classification: WorkloadClassification) -> BuildTemplate:
    if classification.kind is WorkloadKind.STREAMLIT:
        return BuildTemplate(
            kind=classification.kind,
            runtime="python3.13",
            install_command=(
                "python",
                "-m",
                "pip",
                "install",
                "-r",
                "requirements.txt",
            ),
            build_command=(),
            launch_command=(
                "streamlit",
                "run",
                classification.entrypoint,
                "--server.address",
                "0.0.0.0",
                "--server.port",
                "8080",
            ),
            required_files=("app.py", "requirements.txt"),
        )
    if classification.kind is WorkloadKind.NEXTJS:
        return BuildTemplate(
            kind=classification.kind,
            runtime="node20",
            install_command=("npm", "ci", "--ignore-scripts"),
            build_command=("./node_modules/.bin/next", "build"),
            launch_command=(
                "./node_modules/.bin/next",
                "start",
                "--hostname",
                "0.0.0.0",
                "--port",
                "8080",
            ),
            required_files=("app/page.tsx", "package-lock.json", "package.json"),
        )
    if classification.kind is WorkloadKind.SCHEDULED_SCRIPT:
        return BuildTemplate(
            kind=classification.kind,
            runtime="python3.13",
            install_command=(),
            build_command=(),
            launch_command=("python", classification.entrypoint),
            required_files=(classification.entrypoint, "mim.yaml"),
            schedule_cron=classification.schedule_cron,
        )
    raise ValueError("Unsupported workload kind.")
